### PR TITLE
Trans ch cc

### PR DESCRIPTION
**Pull request by Mechtilde**
pull request again. I saw the problem in the "View pull request"  now it should works.

### CODE REVIEW

**Comment by Mechtilde** [comment]
close again. There must be something wrong at my fork on Github

**Comment by jralls** [comment]
The pull request is for the same branch as #22, so if you reused it locally then you need to force-push your changes to github:
 
    git push --force github trans-ch-cc

If you used a different branch for your fix-up then you need to push that to github and delete trans-ch-cc:

    git push github :trans-ch-cc

Note that ':' in front of the branch name, that means "push nothing to trans-ch-cc", which is how git deletes remote branches.

**Comment by Mechtilde** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I renewed the branch and will redo the pull request tomorrow

Am 01.10.2015 um 17:26 schrieb John Ralls:
> The pull request is for the same branch as #22, so if you reused it
> locally then you need to force-push your changes to github:
> 
> git push --force github trans-ch-cc
> 
> If you used a different branch for your fix-up then you need to
> push that to github and delete trans-ch-cc:
> 
> git push github :trans-ch-cc
> 
> Note that ':' in front of the branch name, that means "push nothing
> to trans-ch-cc", which is how git deletes remote branches.
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/Gnucash/gnucash-docs/pull/23#issuecomment-144762226
>
> 
- -- 
Mechtilde Stehmann
## Apache OpenOffice.org
## Freie Office Suite für Linux, MacOSX, Windows
## Loook, calender-exchange-provider, libreoffice-canzeley-client
## PGP encryption welcome
## Key-ID 0x141AAD7F
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCgAGBQJWDXEtAAoJEPKHe7oUGq1/WXMP/RIZHSq4G8pfjnroiP69XYL6
oWJ0oUmEts1iHV+J7L4HAu9dHSj87kCtiRp8iOcj1IFt24p8BmH9w/AdD3o6DhSd
XnC+ul7tGSIrVyKCDoN2goioe0imaEXrgZB7AZDasYKtQCtvwoQjkiPnCu/JTcO7
yiAc0R6+puRpqVHt8m86uDKFdKZxzhcMo7dpqtYxF+DDTYHsZm5XgyiyuQA41wCZ
D3vAcXWlgoQbesvhgc6P4Yo+3wMVHbdT49G98CaBKvLHrWHjgBf3j7fKB5yPrNPU
5iWtjAI45275wiJs5AXltenjLjeVIDtmMgKx9xWjDDKkrmRhaLztkaQhUvgqvxY5
JvH5LtYpFD6tESmGrfQOMHg2rciJhv+pk/HmneJLFDgICyiK9eAemPeut3lKdi3t
xJj5eokYU7Xzot8/CnNOnRBYb5QhuGOZAppXVFMyefzpvTm0EvLu103Lws4Pi3rQ
Ow32nxomeXcHKkEfmvcyYzjxc/a1Spcg81+RG2E/90W1mHU7DB40/KPjESVLl/uy
1CDbFvMJFi3ZmgOdc+zF9EAsiXg/sUS/aV3YXkvU0FqIofWtnbBdQbGBpdsWGxRU
w0xfTZcxw+4gs6Q73SqtwbCpAWjKdzImKdvGq/cf2cchQ/EqUEEOtSpMULSqUTel
MY2CwPPqaSe44JbYGmEd
=Lm7S
-----END PGP SIGNATURE-----

**Comment by jralls** [comment]
Your branch on Github is still derived from master. Not only that but you did a pull from origin and merged commits into the middle of your changes, which will make the mess even harder to clean up. Now before doing the cherry-picking you need to 

    git rebase master trans-ch-cc

to get your changes all together.

**Pull request closed without merging**
