### PR TITLE
Add extra lines to .gitignore so can use netbeans ide xml edit…

### PR DESCRIPTION
**Pull request by goodvibes2**
…or + jEdit

Added .*.marks (jEdit bookmarks), manifest.mf + /nbproject used by netbeans

### CODE REVIEW

**Comment by goodvibes2** [comment]
Closed. Duplicated in https://github.com/Gnucash/gnucash-docs/pull/60

**Comment by goodvibes2** [comment]
As John Ralls now wants me to cancel pull request #60, I'm re-opening this.

**Comment by gjanssens** [comment]
Merged. Enjoy netbeans!

**Comment by goodvibes2** [comment]
Thanks - really appreciate your work :-)

Regards,
Chris Good

**Pull request merged**
