### PR TITLE
Maint

### PR DESCRIPTION
**Pull request by DaveC49**
Created a chapter in the tutorial and concepts guide describing the principles and process of reconciliation of accounts, along with minor modifications to the chapter on transactions describing the reconciliation status to maintain consistency

### CODE REVIEW

**Comment by jralls** [comment]
Huh? This PR doesn't do anything because you twice create a commit and then revert it.

**Comment by DaveC49** [comment]
Apologies John,

I came back to some changes I was in process of developing around reconciliation some time back before I spent the early
part of the year travelling and then realized they had to a large extent been superceded by David T's changes in the
meantime and wouldn't fit in with the reorganization of the guide that has been done so far. I committed  the changes
and created the pull request before realizing this, which was why I then reverted the commit. 

David Cousens

On Mon, 2019-05-20 at 12:23 -0700, John Ralls wrote:
> Huh? This PR doesn't do anything because you twice create a commit and then revert it.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 
Dr David R Cousens
B.Sc, M.Prof. Acc., Ph.D., G.C.Ed

**Comment by jralls** [comment]
David,
OK. I'll close this. You can make a new one if you decide that @sunfish62's docs need amplification.

**Comment by DaveC49** [comment]
Thanks John,

I'll reevaluate what I was proposing and adjust it to fit into the current guide organization. 

David


On Mon, 2019-05-20 at 20:09 -0700, John Ralls wrote:
> David,
> OK. I'll close this. You can make a new one if you decide that @sunfish62's docs need amplification.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 
Dr David R Cousens
B.Sc, M.Prof. Acc., Ph.D., G.C.Ed

**Pull request closed without merging**
