### PR TITLE
Apply new style sheet to docs

### PR DESCRIPTION
**Pull request by usamimikamen-sk**
Apply new xsl to guide and help

### CODE REVIEW

**Comment by CWehli** [comment]
Why did you exclude the changes from the help/de folder?
I am not making any more adjustments to the stylesheets and am concentrating again on the translation of help/de and the backport to help/C.

Please extend this PR to the help/de area as well.

**Comment by usamimikamen-sk** [comment]
> Please extend this PR to the help/de area as well.

I'll do it.

**Comment by usamimikamen-sk** [comment]
d6a65ef
Done.

**Comment by usamimikamen-sk** [comment]
> Please extend this PR to the help/de area as well.
Done.
 d6a65ef

**Comment by usamimikamen-sk** [comment]
I merge this PR into #204.

**Pull request closed without merging**
