### PR TITLE
Proposal: Remove obsolete Appendices pages (FAQ, VAT, AUX file format)

### PR DESCRIPTION
**Pull request by usamimikamen-sk**
I think FAQ, VAT, AUX file format pages in the concepts guide is too old and obsolete.
So I suggest removing them.

I only work some important locations.
If you agree, I will edit other files like cmake.

### CODE REVIEW

**Comment by fellen** [comment]
> AUX file format pages in the concepts guide is too old and obsolete.

Wrong, as nothing changed there, it is up to date.
But as a technical reference it should be moved to help as appendix B.

Do you have an idea for a good place to add the links
https://wiki.gnucash.org/wiki/FAQ
and
https://github.com/Gnucash/gnucash/tree/maint/data/accounts
as replacements?

If we learn, how to 1. check existence of and 2. link /usr/share/help/<LANG>/fdl/ we can also remove the fdl appendix from xml installation.

**Comment by usamimikamen-sk** [comment]
> > AUX file format pages in the concepts guide is too old and obsolete.
> 
> Wrong, as nothing changed there, it is up to date.
> But as a technical reference it should be moved to help as appendix B.

I See. But AUX file format seems to be not for users but for developers.
So I think it will be moved to wiki or API (https://code.gnucash.org/docs/MAINT/).

 
> Do you have an idea for a good place to add the links
> https://wiki.gnucash.org/wiki/FAQ

As for FAQ, please see the guide/C/ch_oview.xml in "File Changed tab".

> https://github.com/Gnucash/gnucash/tree/maint/data/accounts
> as replacements?

TODO

> If we learn, how to 1. check existence of and 2. link /usr/share/help//fdl/ we can also remove the fdl appendix from xml installation.

As for FDL, I'm working now. I'll create PR later.

**Comment by usamimikamen-sk** [comment]
@fellen 
> https://github.com/Gnucash/gnucash/tree/maint/data/accounts
> as replacements?

Why  that URL link is required for the users guide?
Users don't directly access files in that directory. And no user's interface exists to import a XML account hierarchy.
Users can only import an account hierarchy , which is formatted by CSV, by File->Import->Import _Accounts from CSV....

According to https://wiki.gnucash.org/wiki/Account_Hierarchy_Template,  users need root access to use them.

> If we learn, how to 1. check existence of and 2. link /usr/share/help//fdl/ we can also remove the fdl appendix from xml installation.

Which distribution do you use? SuSE? Debian? Fedora?
I'd like to check their contents in that directry.

**Comment by usamimikamen-sk** [comment]
> If we learn, how to 1. check existence of and 2. link /usr/share/help//fdl/ we can also remove the fdl appendix from xml installation.

If you're using GNOME and yelp, try
`<ulink url="help:fdl">FDL</ulink>`.
But it causes some problem.

Technically speaking, it is better to replace appendix when you run
`make lang-docname-gnome`
.

**Comment by jralls** [comment]
@fellen I agree with @usamimikamen-sk that we shouldn't be linking code--regardless of what kind--in the user documentation. The wiki page is the right place for information about the template sources.

@usamimikamen-sk The templates are used by the New Account Hierarchy Assistant which is started by File>New or Actions>New Account Hierarchy. Also you misunderstood the wiki about access to the templates: One needs admin privs to *write* to those directories *if they're system directories*. In other words if you're trying to modify the GnuCash installed by a package manager on Linux/BSD or gnucash-setup.exe on MSWin then you need admin privs. If you built GnuCash yourself and installed it in a directory you own  or installed it with a user-package manager then you don't need admin privs. None of which has anything to do with documenting the templates in the Guide. If you just want to look at them then they're readable without admin privs otherwise GnuCash would have to be run with admin privs to use them.

**Comment by fellen** [comment]
> > > AUX file format pages in the concepts guide is too old and obsolete.
> > 
> > 
> > Wrong, as nothing changed there, it is up to date.
> > But as a technical reference it should be moved to help as appendix B.
> 
> I See. But AUX file format seems to be not for users but for developers.
> So I think it will be moved to wiki or API (https://code.gnucash.org/docs/MAINT/).

No, it describes the chk file format so that users can create and adjust cheque printing to their formulars.

> > Do you have an idea for a good place to add the links
> > https://wiki.gnucash.org/wiki/FAQ
> 
> As for FAQ, please see the guide/C/ch_oview.xml in "File Changed tab".

OK

**Comment by fellen** [comment]
> @fellen
> 
> > https://github.com/Gnucash/gnucash/tree/maint/data/accounts
> > as replacements?

I have now added the link to the wiki page below. So it is here not required.

> Why that URL link is required for the users guide?
> Users don't directly access files in that directory. And no user's interface exists to import a XML account hierarchy.
> Users can only import an account hierarchy , which is formatted by CSV, by File->Import->Import _Accounts from CSV....

Users access that files in the `New Account Hierarchy Setup` at the begin with `New->File` and later by `Action->New Account Hierarchy…`

> According to https://wiki.gnucash.org/wiki/Account_Hierarchy_Template, users need root access to use them.
> 
> > If we learn, how to 1. check existence of and 2. link /usr/share/help//fdl/ we can also remove the fdl appendix from xml installation.
> 
> Which distribution do you use? SuSE? Debian? Fedora?
> I'd like to check their contents in that directory.

Suse.

It  is defined in https://www.freedesktop.org/wiki/Specifications/help-spec/. Directory help is searched in $XDG_DATA_HOME and $XDG_DATA_DIRS. on the next levej subdirectories for languages follow.
$XDG_* variables are defined inin https://specifications.freedesktop.org/basedir-spec/latest/.

**Comment by usamimikamen-sk** [comment]
> No, it describes the chk file format so that users can create and adjust cheque printing to their formulars.

Do you mean users have to see and edit and confirm .chk file directly?
I don't think so that. When users want to print cheques, they will do as follows: 

(1) They buy checkbooks  like  https://orderpoint.deluxe.com/personal-checks/welcome.htm
(2)  They open GnuCash checking account register.
(3) They select File->Print checks...
(4)  They edit options and custom formats for the cheques which they bought.
(5) They press Print button.

That's all. If functionarities are lacking in (4), I agree with you. But if they are enough, I don't think it should be written in the documents for users.

**Comment by derekatkins** [comment]
@usamimikamen-sk  --
> That's all. If functionarities are lacking in (4), I agree with you. But if they are enough, I don't think it should be written in the documents for users.

The CHK format files are absolutely user-configurable.  You are correct that it is not a common thing for a user to do, but it /IS/ something that a user can do.  So this does belong in the user documentation.  It is in an appendix because it's not common.  So in my (not so) humble opinion, it should stay in the documentation.

**Comment by usamimikamen-sk** [comment]
@fellen  and @derekatkins 
I see.  Then it is better to put it into Help manual.
Thank you for your details.

**Comment by usamimikamen-sk** [comment]
@fellen
> > If we learn, how to 1. check existence of and 2. link /usr/share/help//fdl/ we can also remove the fdl appendix from xml installation.

Regarding yelp, the  markup of usamimikamen-sk:dbk branch is correct, so I think it's best not to change it.

**Comment by fellen** [comment]
> @fellen and @derekatkins
> I see. Then it is better to put it into Help manual.
> Thank you for your details.

Perhaps create a separate PR to move it to guide/…/appendixb.xml for all languages.
We should also drop help_ from the filenames in help.

Don't forget to check for links and make files.

**Comment by usamimikamen-sk** [comment]
Close this PR.
See
https://github.com/Gnucash/gnucash-docs/pull/201#issuecomment-898946042

**Comment by usamimikamen-sk** [comment]
> Perhaps create a separate PR to move it to guide/…/appendixb.xml for all languages.
> We should also drop help_ from the filenames in help.
> 
> Don't forget to check for links and make files.

I'll do it after PR #204 and PR #207 are accepted.

**Comment by fellen** [comment]
Redone in PR #210

**Pull request closed without merging**
