### PR TITLE
Update translation

### PR DESCRIPTION
**Pull request by Mechtilde**
This is part I updating translation since one year. More parts will come soon.

### CODE REVIEW

**Comment by fellen** [comment]
Nice work!

Notes:
ch_accts:
 "<guilabel>accounttype:</guilabel>" vs. "<guilabel>accounttype</guilabel>:" should be unique, but which is the right?
BP: <sect2 id="accts-other-types"> Usage of trading accounts is optional.

ch_basics:
 Shouldn't we mark  column headers continuos with <guilabel>...</guilabel> and backport to en_US?

ch_Invest:
- contradictory modification date: were the englisch date not updated? 
- instead of broker (Maklerfirma) or additional  depot bank? Backport?
- security type= exchange doesn't make much sense for Europeans, as the same security may be traded in Frankfurt, Luxemburg, ... E.g. I use shares, funds, options ...{Aktien, Fonds, Optionen, ...} with optional suffix .<currency>, if not noted in EUR.
- Lots: method FiFo: mention § 6 Abs. 1 Nr. 2a. EStG for private users and § 256 HGB for business users: https://www.gesetze-im-internet.de/estg/__6.html ...
! http://www.welt-der-bwl.de/FiFo: Das FiFo-Verfahren ist steuerlich nicht zulässig. (FiFo for income tax not allowed)
 Overview of legal methods in DE: https://de.wikipedia.org/wiki/Verbrauchsfolgeverfahren
Here we need some more research, e.g. ask on gnucash-de in the hope, an CPA will anser.
- Instead of Los-Management-Einrichtung simpy Loseverwaltung?
- -"-             wiederinvestiert reinvestiert?
- "Gewinne oder Verluste" in Advanced Portefolio doesn't exist. Currently we have "[Nicht ]realisierter Gewinn", which is also insufficient we should replace them by "... Ergebnis" in de.po.
- SSSS: based on the german history I would avoid abrreviations with "SS". Is it only used in <sect3 id="invest-sellLotsWin"> or also somewhere else?
-  <sect3 id="invest-sellProcedure">...<orderedlist>: Something was broken in the XRefs, so I commented out the list

commit fd51c5e

**Comment by fellen** [comment]
Hallo Mechtilde,

danke, daß du so emsig bist. Mein offizieller Beitrag folgt via GitHub.
Hier nun eher Tips zur Vorgehensweise.

Irritierend fand ich die zeitlich auseinanderliegenden Änderungen an
makefile.am

Wenn du Änderungen lokal gespeichert hast, laß doch erstmal
 make check
laufen, bevor du sie kommittest. Dann hätte dir der fehlende \, welcher
den Zeilenumbruch maskiert, gleich auffallen müssen.

Auch hinterher kannst du den letzten commit mittels
 git commit -a
(für amendment) nochmal korrigieren.

Dadurch würde es etwas leichter zu lesen.

Guck ruhig über meine Änderungen nochmal drüber, da ich ja noch de:1906
schreibe - das Hin und Her in den 80er und 90er Jahren war mir zu blöd.

LG
Frank

Am 28.11.2016 um 07:47 schrieb Mechtilde:
> This is part I updating translation since one year. More parts will come soon.
> 
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/Gnucash/gnucash-docs/pull/74
> 
> -- Commit Summary --
> 
>   * added ch_expenses.xml and ch_reports.xml
>   * translation of commit 1259a0c4006827fc8b6418a65c8d780c0b26ea14
>   * translation of commit commit df47fc56e6a94d275962366a93fcc977754ad1dd
>   * translation of commit bb525f98b551ac5ab18ba6512f385cbc1af1b184
>   * translation of commit 25d860df72259f48bf532a401ad25a238c6105d5
>   * translation of commit 09b13337cb88a80d832c20509ce5e3a09845d739
>   * initial commit of guide/de/ch_expenses.xml
>   * translation of chapter Expense Accounts
>   * update gnucash-guide.xml
>   * corrected Makefile.am
>   * translate commit c768b012db3216d835f1f4e3220ce75323cf7904 and add Englih screenshot
>   * translate commit 2ba657161c81c66afc8ecabb79c1d6df2b4010b4
>   * Part I from commit 1d753e94eebb107470514a67f246a767736ad572
>   * Part II - translation of commit 1d753e94eebb107470514a67f246a767736ad572
>   * adoption to the first pull request
>   * mask links which can't refer to
>   * prepared for PR
> 
> -- File Changes --
> 
>     M guide/de/Makefile.am (1)
>     M guide/de/ch_accts.xml (29)
>     M guide/de/ch_basics.xml (11)
>     A guide/de/ch_expenses.xml (96)
>     M guide/de/ch_invest.xml (1059)
>     M guide/de/ch_txns.xml (52)
>     A guide/de/figures/investLots2_BeforeScrub1Lot.png (0)
>     A guide/de/figures/invest_ret_of_cap.png (0)
>     M guide/de/gnucash-guide.xml (50)
> 
> -- Patch Links --
> 
> https://github.com/Gnucash/gnucash-docs/pull/74.patch
> https://github.com/Gnucash/gnucash-docs/pull/74.diff
>

**Comment by fellen** [comment]
Oops, reply to wrong address, sorry for the inconvenience.

**Comment by fellen** [comment]
Is there a way to mark it as merged?

**Comment by jralls** [comment]
Not manually. If you can merge it without changes then Github will notice and mark it merged on its own, otherwise we (meaning Geert and I) usually say that we merged with a rebase or with changes or whatever when we close the PR. It's better if the merge commit says something like "Merge of Mechtilde's Updated German Translation." or "Merge of PR 74." rather than "Review of...".

**Comment by jralls** [comment]
This has been merged.

**Pull request closed without merging**
