### PR TITLE
Fixes reference to Security Editor on Help Manual

### PR DESCRIPTION
**Pull request by igorlvicente**
Let me know if the PR requires more than just that.

### CODE REVIEW

**Comment by fellen** [comment]
Hi,
nice to apply it in all languages!
That will fix it for now, but inserting or removing a chapter before the the target will break it  again.
A link would then update its description.

if it were in the same document, we could use `<xref linkend="">` here.
The proper links to other documents are olinks, but we have to set them properly up in the build process. 

Until that is done, we can use a link to the document on the build server:
`<ulink url="&url-docs-build-C;help/tool-security-edit.html">content of quote</ulink>`
"C" is the language symbol for english and should be replaced
like replace
`na secção 7.7, <quote>Editor de mercadorias</quote>.`
by
`na secção <ulink url="&url-docs-build-pt;help/tool-security-edit.html">Editor de mercadorias</ulink>.`

Do you want to improve it?

**Comment by fellen** [comment]
For now I have merged it – thanks!

Do have plans to improve it like i described?

**Comment by igorlvicente** [comment]
Yes, I want to improve it but I don't know when I will be able to.

**Comment by fellen** [comment]
Don't hurry. And ask if something is not obvisiuos. When you are ready create a new PR.

**Pull request merged**
