### PR TITLE
L10N:de: guide: according Bug 777318 (already closed for a long time)

### PR DESCRIPTION
**Pull request by jralls**
Recreate #298 
- Restructure Business Features Chapters.

### CODE REVIEW

**Comment by CWehli** [comment]
@fellen: Just have a look

**Comment by CWehli** [comment]
@fellen please review. I've only made changes to the structure and not to the content.

**Comment by CWehli** [comment]
@jralls, @fell, in my opinion, this PR is complete and ready to merge.

**Comment by fellen** [comment]
I will trust you. Thanks!

**Pull request merged**
