### PR TITLE
Bug755174 document using lots to calculate investment capital gains

### PR DESCRIPTION
**Pull request by goodvibes2**
I also included mods to .gitignore that were also in my previous adjust-dpi pull request again. Sorry, I got into a git loop and thought this was the best way out. I hope because the .gitignore mods are a separate commit, it won't cause problems.

Um... Why does it say: 
goodvibes2  wants to merge 67 commits into Gnucash:maint  from goodvibes2:bug755174DocViewLots ?

It should be just the last 4 commits from today...

### CODE REVIEW

**Comment by jralls** [comment]
I see the problem: You merged master into your local maint branch at e531cec. Here's how to fix it:
```
git reset --hard 8fb4738                  # Roll back to before the bad merge
git pull --rebase  upstream              # Make sure your local branch is in sync with upstream;      
                                                           # assumes that you're using Geert's naming scheme.
git cherry-pick 982700f..5b8d452  # Re-apply your new commits.
git push --force github maint           # Fix your github repo.
```

Having 2 PRs from the same branch doesn't make sense to github. The PR is by branch so any update you make to the branch shows up in the PR. Just clean up your mess, close one of the PRs, and I'll have a look at the changes. It's too hard to review with all of the extra commits in there.

**Comment by goodvibes2** [comment]
Hi John,
Thanks of the help.

git reset --hard 8fb4738
fatal: ambiguous argument '8fb4738': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

I cannot find commit 8fb4738 in any branch.
I thought it should be e6ef0a7e	which worked with git reset
but when I did
git pull --rebase  upstream maint
there were conflicts which I gave up trying to fix on the 3rd file which was in german.

I'm going to close my 2 pull requests and start again as I have all my modified files saved in Dropbox.
Thanks again. Chris

**Comment by jralls** [comment]
Chris, 

Sorry for the typo, it should be ```git reset --hard 8fb47e8```.  **e** instead of **3**
in the next-to-last position.

e6ef0a7 is the one that's the problem: Merging master into maint brought over all of the changes from master -- which in docs is mostly merges from maint so there's no real affect on the content but it makes a mess of history. You want to reset to the change just before that.

Once you've committed a change it's in your repo until you do a ```git gc``` to clean up commits that aren't part of any branch or make 100 commits at which point git will do that for you. No need to rely on dropbox.

**Comment by goodvibes2** [comment]
John,
I tried again using 8fb47e8 instead of 8fb4738
git checkout maint
git reset --hard 8fb47e8
  HEAD is now at 8fb47e8 Update partial date entry documentation based on new default behaviour
git pull --rebase  upstream maint
...
    CONFLICT (content): Merge conflict in configure.ac
	Patch failed at 0001 Set version on master to 2.6.99
    CONFLICT (content): Merge conflict in help/C/Help_ch_Reports.xml
	Patch failed at 0002 Help for budget report.

It seems the same conflicts are happening again.
Unfortunately I didn't note the commits that were conflicting but the 2nd seems to be:
master commit 6a5083c368c8b8306231c1aa6e333ceb4e359508
Author: Dmitry Pavlov <zeldigas@gmail.com>
Date:   Sun Mar 2 01:26:00 2014 +0400
Help for budget report.
Include base description + updates for ranged report generation improvement

2014 seems old.. Anyway, I've recreated my repo now.
Regards, Chris Good

**Comment by jralls** [comment]
Yeah, stupid me. 8fb47e8 is from master. The commit that you needed was the one from the maint branch just before the merge; that's not recoverable now that you recreated your repo, but that also makes it moot. Sorry for leading you astray.

**Pull request closed without merging**
