### PR TITLE
Patch to add note for Balance Column resize (Bug 762656)

### PR DESCRIPTION
**Pull request by sunfish62**

### CODE REVIEW

**Comment by jralls** [comment]
Thanks, merged with a minor fix: We use the <guilabel> element for column headers rather than <emphasis>.

**Comment by sunfish62** [comment]
Thanks John. Could you tell me again what alterations you made? The XML got eaten...

**Comment by jralls** [comment]
Look at [your commit in the gnucash mirror](https://github.com/Gnucash/gnucash-docs/commit/1259a0c4006827fc8b6418a65c8d780c0b26ea14) and you'll see that I replaced ```<emphasis>...</emphasis>``` with ```<guilabel>...</guilabel>``` in two places.

**Comment by sunfish62** [comment]
Ah. I tried that, but didn't notice the tag difference. Thanks.

**Pull request closed without merging**
