### PR TITLE
Bug 797950 Reconcilation docs don't mention automatic credit card payment feature.

### PR DESCRIPTION
**Pull request by CWehli**
The german translation is included in commit 218e284, PR #178.

### CODE REVIEW

**Comment by fellen** [comment]
Do you know already a backport of which commit/PR in de it is?

**Comment by CWehli** [comment]
I have included the german description for the bug in commit 218e28464d1a282db0e0af451296fa503b3da437. This is the PR #178.

**Comment by fellen** [comment]
> I have included the german description for the bug in commit [218e284](https://github.com/Gnucash/gnucash-docs/commit/218e28464d1a282db0e0af451296fa503b3da437). This is the PR #178.

Then add it as line 3 to the commit message

**Review by fellen — APPROVED** [review]

**Comment by fellen** [comment]
Thanks!

**Comment by fellen** [comment]
Sill one note: while it is OK to fix only the sections currently in progress,the commit message should then contain `Bug xxx part n`.

**Pull request merged**
