### PR TITLE
Update for sample-report

### PR DESCRIPTION
**Pull request by flywire**

### CODE REVIEW

**Comment by flywire** [comment]
This is required following https://github.com/Gnucash/gnucash/commit/f292ebee477c41f8936a48e45a42109886a43550 to keep docs consistent with app.

**Comment by flywire** [comment]
Another section needs updating but the string freeze might affect it: https://github.com/Gnucash/gnucash-docs/blob/6e2a0aba5748a866c7d841625423a50943754769/C/manual/ch_Reports.xml#L2866-L2888

Should contain:
* sample-report: Sample Report
* sample-graphs: Sample Graphs
* average-balance: Average Balance
* daily-reports: Income vs. Day of Week, Expenses vs. Day of Week

**Comment by jralls** [comment]
The string freeze doesn't affect docs.

**Comment by jralls** [comment]
Thanks!

**Pull request merged**
