### PR TITLE
(7)Change install directory to  ${PREFIX}/share/help/${lang}/${docname} for Yelp.

### PR DESCRIPTION
**Pull request by usamimikamen-sk**
depends on PR #220.
---
The gnucash-guide and gnucash-help were not shown in yelp though we ran make install.
This PR fixes this problem.

If this PR is applied, the guide and help will be shown in the TOC of Yelp. But they won't be shown in the TOC of the KDE help center.

I can't afford to look up the KDE help center. So I wish someone could create metadata for the KDE help center.
See https://github.com/KDE/khelpcenter.

John Ralls said in Bug#798166 that IMO it was stupid to change anything but AddGHelpTarget.cmake in support of the Yelp build target. And I think it is right. So changing AddGHelpTarget.cmake or creating AddKHelpTarget.cmake is the good method.

This change is in accordance with the XDG help-system-spec. But the KDE help center won't recognize the guide and help. I can't believe XDG specification.

---
This PR depends on PR #220.

### CODE REVIEW

**Review by gjanssens — COMMENTED** [review]
I'm not too happy you chose to disregard my branch and reimplemented the changes again yourself.

**Comment by fellen** [comment]
> I'm not too happy you chose to disregard my branch and reimplemented the changes again yourself.

You didn't publish it here as PR. ;-)

**Comment by fellen** [comment]
> John Ralls said in Bug#798166 that IMO it was stupid to change anything but AddGHelpTarget.cmake in support of the Yelp build target. And I think it is right. So changing AddGHelpTarget.cmake or creating AddKHelpTarget.cmake is the good method.

And I fear, we get a problem to fix [Bug 797426 - Make glossary of GnuCash terms available for use in both the Guide and help manual](https://bugs.gnucash.org/show_bug.cgi?id=797426) if we have not the same layout in the source and install directory.

**Comment by fellen** [comment]
Redone in PR #235

**Pull request closed without merging**
