### PR TITLE
Calculate price if importing securities

### PR DESCRIPTION
**Pull request by flywire**
https://bugs.gnucash.org/show_bug.cgi?id=797450#c9

### CODE REVIEW

**Comment by jralls** [comment]
I think this needs some more explanation in the introduction, perhaps as a note about importing transactions in more than one commodity. Although it's not mentioned in the particular bug reports, the CSV importer can also mess up transactions with more than two commodities unless the Transaction Commodity column is populated because it may pick the wrong split's commodity for the transaction commodity.  The Deposit and Withdrawal columns need to explicitly say that the amounts are treated as being in the transfer account's commodity and the conversion to the transaction currency is calculated by price * (deposit - withdrawal).

You might also mention that if a price is needed and the price column is empty or 0 that the importer will look for a price in the pricedb and fall back on 1 as a last resort.

**Comment by flywire** [comment]
I agree the commodity explaination is fairly poor but I don't consider my experience with them sufficient to offer an explanation. I don't see that precludes an explanation of how to enter a price.

**Comment by fellen** [comment]
> I think this needs some more explanation in the introduction, perhaps as a note about importing transactions in more than one commodity. Although it's not mentioned in the particular bug reports, the CSV importer can also mess up transactions with more than two commodities unless the Transaction Commodity column is populated because it may pick the wrong split's commodity for the transaction commodity. The Deposit and Withdrawal columns need to explicitly say that the amounts are treated as being in the transfer account's commodity and the conversion to the transaction currency is calculated by price * (deposit - withdrawal).
> 
> You might also mention that if a price is needed and the price column is empty or 0 that the importer will look for a price in the pricedb and fall back on 1 as a last resort.

To avoid redundancies the basic details should be explained in the multi-currency chapter and then it should be linked from here. And this secion should only get the import specific part.

@flywire see https://wiki.gnucash.org/wiki/Documentation_Improvement for details and ust reiterate what John told here.

**Comment by flywire** [comment]
> the CSV importer can also mess up transactions with more than two commodities

When I saw that I realised I'm not competent with this functionality. I suppose it is purchase securities with foreign currency, not something I'd likely use and best left for someone else to explain.

**Pull request closed without merging**
