### PR TITLE
Bug 781711: Add reversing transaction definition

### PR DESCRIPTION
**Pull request by sunfish62**

### CODE REVIEW

**Comment by gjanssens** [comment]
Thanks!

**Comment by fellen** [comment]
Just a note:
 "restores the books to the state before the error" could be read as 
"you will loose all transactions made in between".

**Comment by sunfish62** [comment]
Good point. How about:
"This reversing transaction duplicates the original transaction, but with debit and credit amounts reversed. This removes the effect of the erroneous transaction from the books. After entering the reversing transaction, a corrected transaction can then be entered."

A little more wordy, but less ambiguous.

**Comment by fellen** [comment]
commit eded1c2
Thanks!

**Pull request merged**
