### PR TITLE
Fix 1 remaining 'incomes'

### PR DESCRIPTION
**Pull request by phil-davis**

### CODE REVIEW

**Comment by gjanssens** [comment]
Thanks. It will be part of the next release. It missed 2.6.17 by a day...

**Comment by phil-davis** [comment]
Yes, I saw the release notification on the mailing list and that made me go looking at diffs in the docs - by definition too late.

**Comment by fellen** [comment]
Just for curiosity: are such mixed forms of singular and plural really common in English?

**Comment by jralls** [comment]
There are a [few irregulars](https://www.vappingo.com/word-blog/101-words-that-are-both-plural-and-singular/). 'Income' isn't really one of them, though. It gets the plural form only if it's the object and the subject is plural.

**Comment by phil-davis** [comment]
Basic summary of English: its a mess.

**Pull request merged**
