### PR TITLE
(4a) Set attribute of *list spacing="compact" for FO/PDF.

### PR DESCRIPTION
**Pull request by usamimikamen-sk**
Depends on #211
---
This is requested by @CWehli in https://github.com/Gnucash/gnucash-docs/pull/211#issuecomment-923815297.
This PR is for FO/PDF only.

I'll create another PR for HTML(s) because it is a bit complex to do.
It becomes clear by using external CSS. So I have to set some parameters, create CSS file, and change cmake files.

### CODE REVIEW

**Comment by usamimikamen-sk** [comment]
unspecified
compact

**Comment by CWehli** [comment]
@usamimikamen-sk 
Thanks.
> This PR is for FO/PDF only.

Do you have the possibility to underline the links in fo/pdf? (like a hyperlink in HTML)

**Comment by usamimikamen-sk** [comment]
> Do you have the possibility to underline the links in fo/pdf? (like a hyperlink in HTML)

@CWehli 

There are three types of links in PDF.
(1) `See 1.1 title` (xref title)
(2) table of contents
(3) `The Free Software Foundation [http://www.gnu.org/fsf/fsf.html] ` (ulink external URL in the brackets)

Which links?

**Comment by CWehli** [comment]
@usamimikamen-sk 
> (1) `See 1.1 title` (xref title)
> (2) table of contents
> (3) `The Free Software Foundation [http://www.gnu.org/fsf/fsf.html] `

I think for numbers 1 and 3 the underlining makes sense.
In TOC, the link must work, but I don't like the underlining there.

**Comment by fellen** [comment]
From my understanding in pdf because of its paper origin it is more common to append square brackets with the links.

**Comment by CWehli** [comment]
>  square brackets with the links.

This is also ok for me, but it is important that such links are visually highlighted.

**Comment by fellen** [comment]
> [Edit] I think there is also a bug entry for this. [/Edit]

[Bug 796854 - Internal document links are not visually discoverable in PDF - need separate styling](https://bugs.gnucash.org/show_bug.cgi?id=796854)

**Pull request closed without merging**
