### PR TITLE
Importing data example

### PR DESCRIPTION
**Pull request by flywire**
This is a placeholder developed from the  [initial concept](https://chat.stackexchange.com/transcript/message/54159828#54159828). Comments are sought before finalising and formatting.

----------

 **Putting It All Together**

Manual data entry is slow and error-prone, and this section uses a Checking Account bank statement to demonstrate quickly loading much of the transaction data, allowing the user to concentrate on those transactions that need more careful consideration. A typical situation is loading hundreds of transactions to create a new cashbook file. The same transactions are used as the previous chapter and references are made to those sections where more specific processing (eg splits) is required to process the transactions. Other accounts could use a similar process.

This chapter is not intended to replace [Chapter 2, "The Basics"]( https://www.gnucash.org/docs/v3/C/gnucash-guide/chapter_basics.html) which introduces some of the basics of using GnuCash. It is recommended that you read through that chapter, before starting to do any real work with GnuCash. In particular, the sections on Accounts and Transactions are particularly relevant to importing data from file so you understand what it means and how it works.

**Build chart of accounts**

A new file is required with accounts as described in the previous chapter. The chapter finished with a tutorial which created _gcashdata_3emptyAccts_ which you could use now.

Alternatively, Import CSV can be a quick way of creating a new file and building the chart of accounts. Save the following data to _AccountTree.csv_ which contains the minimum fields to create accounts:
    
~~~   
type,full_name,name,code,description,color,notes,commoditym,commodityn,hidden,tax,placeholder
ASSET,Assets,Assets,,,,,AUD,CURRENCY,,,
CASH,Assets:Cash,Cash,,,,,AUD,CURRENCY,,,
BANK,Assets:Checking,Checking,,,,,AUD,CURRENCY,,,
BANK,Assets:Savings,Savings,,,,,AUD,CURRENCY,,,
LIABILITY,Liabilities,Liabilities,,,,,AUD,CURRENCY,,,
CREDIT,Liabilities:Visa,Visa,,,,,AUD,CURRENCY,,,
INCOME,Income,Income,,,,,AUD,CURRENCY,,,
INCOME,Income:Salary,Salary,,,,,AUD,CURRENCY,,,
EXPENSE,Expenses,Expenses,,,,,AUD,CURRENCY,,,
EXPENSE,Expenses:Electricity,Electricity,,,,,AUD,CURRENCY,,,
EXPENSE,Expenses:Groceries,Groceries,,,,,AUD,CURRENCY,,,
EXPENSE,Expenses:Internet,Internet,,,,,AUD,CURRENCY,,,
EXPENSE,Expenses:Phone,Phone,,,,,AUD,CURRENCY,,,
EXPENSE,Expenses:Rent,Rent,,,,,AUD,CURRENCY,,,
EXPENSE,Expenses:Taxes,Taxes,,,,,AUD,CURRENCY,,,
EXPENSE,Expenses:Taxes:Federal,Federal,,,,,AUD,CURRENCY,,,
EXPENSE,Expenses:Taxes:Medicare,Medicare,,,,,AUD,CURRENCY,,,
EXPENSE,Expenses:Taxes:Social Security,Social Security,,,,,AUD,CURRENCY,,,
EQUITY,Equity,Equity,,,,,AUD,CURRENCY,,,
EQUITY,Equity:Opening Balance,Opening Balance,,,,,AUD,CURRENCY,,,
~~~

Start a new file: File, New File, Cancel

Create the Accounts: File, Import, Import Accounts From CSV...
which will open up the Import Account Assistant at the introductory Tab.
Choose File to Import, _AccountTree.csv_
Import Account Preview, Header rows must be skipped even if they contain field names, Comma Separated
The accounts will be imported after clicking 'Apply', and
a summary will be displayed Hopefully, Displaying "Import completed successfully!"

New Book Options opens which are described elsewhere in the guide.

Save this chart of accounts with the name _gcashdata_3emptyAccts_, as we will continue to use it.

**Importing a Bank Statement**

The following file is typical of a checkbook statement. Note in this instance fields are separated by tabs instead of commas.

~~~
Date	Number	Description	Amount	Balance
05/03/06	101	GG25j1546 Groceries    wtf 15:57 061124	-45.21	413.05
06/03/06		Transfer to J&J Doe Savings Acc 5765-8397 589654259587	100.00	513.05
14/03/06		Direct Credit Salary from Employers R Us	670.00	1,183.05
28/03/06		Mmvoin515b  Internet Company bg??	-20.00	1,163.05
28/03/06	102	Light Company Big City Branch   9g8k863	-78.00	1,085.05
28/03/06	103	Phone Company Name    Autodebit 595642583	-45.00	1,040.05
28/03/06	104	Internet Transfer         April Rent 5 Short Road	-350.00	690.05
~~~

The good things about bank data are the transaction dates, numbers (if used) and amounts. A lot more data is required in a cashbook which is normally got by decoding the description to determine the payee and account, and the class and memo if they are used. This decoding can be slow and error-prone so a preprocessor can make the process more accurate and efficient.

This guide assumes a preprocessor is used to enrich the bank statement before it is imported. You can use a spreadsheet, python program, or search for another program to process the files. Save the following data to _CheckStatementEnriched.csv_ which has Account and Payee fields added:

~~~
Date,Number,Memo,Amount,Balance,Account,Entity
05/03/06,101,GG25j1546 Groceries    wtf 15:57 061124,-45.21,413.05,Expenses:Groceries,Big Food
06/03/06,,Transfer to J&J Doe Savings Acc 5765-8397 589654259587,100,513.05,Assets:Savings,[Savings]
14/03/06,,Direct Credit Salary from Employers R Us,670,1183.05,Income:Salary,Employers R Us
28/03/06,,Mmvoin515b  Internet Company bg??,-20,1163.05,Expenses:Internet,FastFibre
28/03/06,102,Light Company Big City Branch   9g8k863,-78,185.05,Expenses:Electricity,Light Company
28/03/06,103,Phone Company Name    Autodebit 595642583,-45,140.05,Expenses:Phone,Phone Company Name
28/03/06,104,April Rent        5 Short Road,-350,690.05,Expenses:Rent,HighTower
~~~

If you don't have _gcashdata_3emptyAccts_ open then open it now and use File, Save As... _gcashfile_2_

Create the Accounts: File, Import, Import Transactions From CSV...
which will open up the Transaction Import Assistant at the introductory Tab.
Next to select File to import: _CheckStatementEnriched.csv_
Enter Account - Assets:Checking
Select Date Format - d-m-y
Leading Lines to skip - 1 (header line is not processed)
Enter fields - Minimum: 
Date - Date, Number - Num, Memo - Memo, Amount - Deposit, Balance - None, Account - Transfer Account, Entity - Description
Next to Match Import and GnuCash accounts.
Double click on a row 

The transactions loaded need to be verified to fix the errors in the accounts being guided by the process in [Section 2.9, "Transactions"]( https://www.gnucash.org/docs/v3/C/gnucash-guide/chapter_txns.html). Verification is done by looking at each transaction and fixing the errors.

Two things importing bank statements don't do are starting balances and splits. The Checking account opening balance can be entered as shown in [Section 2.9.3.1, “Simple Transaction Example”](https://www.gnucash.org/docs/v3/C/gnucash-guide/chapter_txns.html#txns-registers-twoaccount2). The salary payment has the wrong salary and tax. Enter the splits following [Section 2.9.3.2, "Split Transaction Example"](https://www.gnucash.org/docs/v3/C/gnucash-guide/chapter_txns.html#BROKEN-LINK).

This process allows quick entry of hundreds of transactions from bank statements with fewer data entry errors.

### CODE REVIEW

**Comment by jralls** [comment]
We don't use the term "cashbook". The usual meaning of that is a record of cash, i.e. physical currency notes and coins. 

Your assumption of some sort of unspecified preprocessor for CSV files rather reduces the utility of the proposed section, as GnuCash doesn't provide such a preprocessor and only a few GnuCash users would be able to write one for themselves. The rest of the proposed section is largely free of useful content. The grammar and usage are of a standard far lower than most such contributions.

**Comment by flywire** [comment]
The use case is a user that has a few years of transactions they'd like to analyse, perhaps with budgeting in mind. It's not unusual.

- Where is the brief tutorial documentation to help a user in this situation?
- I'm not aware of any documented way of quickly building a chart of accounts, and with the [Request More Flexible Import Accounts From CSV](https://bugs.gnucash.org/show_bug.cgi?id=797699) it would be too easy. Even documentation on _Import Accounts From CSV_ is almost absent.
- The _Importing Data into GnuCash_ section certainly doesn't work like any other csv importer, and could really benefit from a _Putting It All Together_ part.
- The process doesn't rely on any particular preprocessor, but they are available, including the template I put together. Still, I take your point that nothing does it well (although qifqif offered promise).
- The intention is to ensure it is consistent with the rest of the guide to the file level and not rewrite existing sections that are well documented.

@jrails I assume your main style concern is the way the interface commands are presented as notes recorded as I went through the steps. This is deliberately put up for feedback before putting effort into grammar, terminology and document coding.

All feedback is welcome but constructive feedback would be better. eg We normally use the term double-entry accounting file [or whatever] because cashbook usually refers to physical currency would be better. _We_ (the community form) aren't even consistent on the term guide/manual/book in the same document.

**Comment by flywire** [comment]
@DaveC49 fyi, just saw [Rewrite of Guide Importing Transactions](https://bugs.gnucash.org/show_bug.cgi?id=797439)

**Comment by jralls** [comment]
@flywire I understand the use case and documenting it is worthwhile.

It's still not clear to me whether what you've written in plain text is an outline or is the entirety of what you intend to write, lacking only the Docbook markup. If the latter, it's not acceptable. If it's 
 really the former as a starting point for discussion then there's plenty of room for discussion.

 I picked out cashbook in particular because it's restrictive. I tend to use simply *book* for the conceptual level in contrast to *file* or *database* to mean the stored contents of the book. Others often use *database* for the conceptual level but that can be confusing to readers for whom the word means primarily the sort of rows-and-columns-in-tables sort.

The proposed example doesn't "put it all together", nor can it: The existing section is too bare-bones and in the case of CSV also obsolete. Your offering illustrates converting a tab-separated bank statement (where'd that come from?) that needs some unspecified pre-processing (not really described) to fill in some information using terms some of which are not used the same way in GnuCash code nor in other documentation (e.g. "payee" applies to invoices but not to bank accounts; "class" isn't used at all as a field). All in all it might fit your use case but we (the GnuCash core team) have generally recommended financial software specific formats like QIF, OFX, or MT940. Until GnuCash 3.x the CSV importer was too limited for general importing, though it was capable of simple bank-statement like formats. What's more, those importers feed their results through the matcher which makes it pretty easy to select the transfer accounts for the first few files, after which they are able to make pretty good guesses for transactions with similar descriptions.

I'd strongly recommend against using a CSV import to set up a chart of accounts: We have a very good set of template accounts localized for 39 countries--though not all of the locales have a full complement of account selections. One can create a pretty comprehensive CoA complete with starting balances in a few minutes. The only widely-used section that can't be generated that way is an investment portfolio, but since there's no way to import commodity definitions for the various securities importing an account tree from CSV won't help much either.

**Comment by DaveC49** [comment]
I haven't progressed very far with https://bugs.gnucash.org/show_bug.cgi?id=797439 after some inital work on  exporting the multiline transaction in full format - travelling, publishing my wife's poetry and minor health issues got in the way for a while and I've only recently made it back to working on GnuCash. The importing at the moment baulks at importing multicurrency and possibly stock transactions mainly because of what appears to be an issue with parsing price data expressed in a rational fraction format.

**Comment by flywire** [comment]
@DaveC49 Thanks for the update but you have obviously thought about it a bit.

@jralls The original request was for comment (ie feedback, collaboration). There wasn't much beforehand but it certainly wasn't done without consideration, some of which is described below. One outcome may well be someone providing a reference where the use case is well covered.

Everything you raised can be addressed, particularly in the discussion.

Book is in the glossary but it is a really vague, even in the [GnuCash Tutorial and Concepts] Guide it also refers to the document itself. 

> Finally, a “Putting It All Together” section ends the chapter by giving detailed, concrete examples.

That section name was already adopted but it contains _examples_ as per this PR title. Collectively, tutorial is a generalised word for it. Something as long as required to demonstrate the functionality and no longer.

I totally disagree that [csv](https://en.wikipedia.org/wiki/Comma-separated_values) is obsolete, it is too widely used in many different platforms. The other formats are restricted to financial platforms. You can map your top ten sales in a GIS with csv but I doubt qif. The tabular format is easy to work with, in say a spreadsheet, and even present in a tutorial document.

Despite the glossary, csv is recognised as a [fairly loose format](https://en.wikipedia.org/wiki/Comma-separated_values#Specification) which includes tabs as field separators, including by banks and GnuCash:

image

> This guide assumes a preprocessor is used to enrich the bank statement before it is imported.

It doesn't actually _need_ any enhancements but hopefully, the advantage of doing that can be demonstrated. As you say, there are built-in facilities but there are advantages to uploading a file without uncontrolled user input. An errant keystroke with the built-in parser will be attached to many records whereas a preprocessor can just be rerun.

The other formats are probably too complex for most users to manipulate so hardly worth demonstrating and the data can't be conveniently printed in a document.

The intention is to setup a _book_ which is "consistent with the rest of the guide to the file level" to import csv transactions. _Import Accounts From CSV_ does that simply in the text. Your recommendation re CoA is noted and that can be emphasised in the text.

**Comment by fellen** [comment]
> **Putting It All Together**

The original author used it as title of the _last_ `<section1>` of a chapter and it contained the exercise for the theoretical part before.
You would better use `<abstract>` here.

**Comment by jralls** [comment]
@flywire 
> I totally disagree that csv is obsolete, it is too widely used in many different platforms.

No argument, you misunderstood me. I meant that the *documentation* for CSV import in section `3.1.5` is obsolete. It isn't actually, I just thought that it was left over from before @gjanssens's rewrite of the CSV importer because of the import documentation gyrations from 2 years ago. In fact @DaveC49 wrote it from scratch as part of that, it's just that it appears in two places.

Yes, the other formats are financial software only. I don't see why that's a problem, GnuCash is financial software.

> The intention is to setup a book which is "consistent with the rest of the guide to the file level" to import csv transactions. Import Accounts From CSV does that simply in the text. Your recommendation re CoA is noted and that can be emphasised in the text.

Since the rest of the *Tutorial and Concepts Guide* uses templates to set up a CoA if you want to be consistent you should have done the same.

**Comment by flywire** [comment]
> Since the rest of the _Tutorial and Concepts Guide_ uses templates to set up a CoA if you want to be consistent you should have done the same.

No.

Let's examine this to "ensure it is consistent with the rest of the guide to the file level".

The intention is to use bank statements [provided as part of the excercise] to enter the transactions used in [2.9.6. Putting It All Together](https://www.gnucash.org/docs/v3/C/gnucash-guide/chapter_txns.html#txns-puttoget1)... "_Start with opening the previous datafile we stored, gcashdata_3emptyAccts_". (Click above link to verify.)

[2.8.3. Putting It All Together](https://www.gnucash.org/docs/v3/C/gnucash-guide/chapter_accts.html#accts-examples1)
"_Let’s go through the process of building a common personal finance chart of accounts_" [then at the end of this section] ... "_Save this chart of accounts with the name gcashdata_3, as well as gcashdata_3emptyAccts_".

The data in the tutorial is an export of that chart of accounts. It is a really simple way of demonstrating importing a csv file, especially given:
- _Import Accounts From CSV_ is not presented anywhere else
- csv import is not as flexible as other systems
- this very simple visual data format easily demonstrated the _Importing Data into GnuCash_ chapter
- it is a good lead to the more complicated second part of the exercise, suggesting enhancing the csv file before importing is more efficient
- the concerns about importing CoAs can be emphasised in the text.

There is a strong case to use a csv import here, even if CoA templates were used elsewhere.

-----

- Acceptance of use case being worth documenting is noted. To reiterate my comment above, the exercise was carefully considered even though the words weren't. The style needs to be consistent with the rest of the guide it uses which wouldn't have been worth doing if the exercise wasn't accepted.
- I agree with another comment provided elsewhere that the bank statement data still looks too much like a chart of accounts.
- Is there an issue with the exercise using  Save As... gcashfile_**2** given it is not used but comes after using 3 and before 4?
- Terminology is a big issue in the industry. The average person would be more likely to associate the term _cashbook_ with a Financial Management System than _book_ or _file_. Anyway, consistency is more important.

**Comment by flywire** [comment]
> The importing at the moment baulks at importing multicurrency and possibly stock transactions mainly because of what appears to be an issue with parsing price data expressed in a rational fraction format.

Off-topic but It should keep it in the currency it is held in.

**Comment by fellen** [comment]
Some general thoughts:

While the help/manual should show technical details, e.g. GUI elements, the tutorial should be more task oriented: After the introduction containing fundamental knowledge of accounting, the chapters should show "How can I reach Task X using GnuCash?".
Importing is used in 2 different tasks:

- Migrating to gnucash, ideally with subchapters:
-- from another financial app [QIF]
--  from a spreadsheet [CSV]
- Update Bank statements
-- from downloaded files
-- using AqBanking

**Comment by gjanssens** [comment]
> The importing at the moment baulks at importing multicurrency and possibly stock transactions mainly because of what appears to be an issue with parsing price data expressed in a rational fraction format.

Single line imports still don't work but for other reasons. Multiline imports got a fix in 3.10 which should now in theory be able to import foreign currency splits.

There are still gotchas
* if you import data which doesn't have a transaction currency column, the transaction gets the currency from its first split. This is not always what you would want. Workaround is to provide a currency column.
* Single single line imports need more work to get multi currency imports working.

**Comment by flywire** [comment]
I've read the manual but I still don't understand the concept of matching.
- If data is tagged with an account why does the account need to be matched with identical GnuCash accounts [exported from GnuCash]?
- Why is transaction matching required?
- Furthermore, if one transaction is matched in a list. Why isn't the transaction list updated to match other identical transactions matched?

**Comment by jralls** [comment]
> If data is tagged with an account why does the account need to be matched with identical GnuCash accounts [exported from GnuCash]?

Sorry, do you mean if the CSV already has the "other" account why does it need to run the matcher? I don't think that it does. @gjanssens?

> Why is transaction matching required?

Because many, perhaps even most, imports don't have the "other" account identified, just a description. That's the case for your bank account example. The matcher, once trained, provides automatic assignment of the "other" account based on the description.

> Furthermore, if one transaction is matched in a list. Why isn't the transaction list updated to match other identical transactions matched?

Because matching a transaction list takes significant time and re-running it every time a user matched a transaction would be annoyingly slow. So it works the other way around as of IIRC 3.7 or so but that's not yet documented: You can select several transactions at once in the matcher and right-click for a context menu with the single entry for picking a matching account for all of the selected transactions. Once the matcher is trained it will match all of the transactions.

**Comment by jralls** [comment]
> Import Accounts From CSV is not presented anywhere else

Then it should be *before* being used in an example--especially one titled "Pulling it all together".

**Comment by gjanssens** [comment]
> > If data is tagged with an account why does the account need to be matched with identical GnuCash accounts [exported from GnuCash]?
> 
> Sorry, do you mean if the CSV already has the "other" account why does it need to run the matcher? I don't think that it does. @gjanssens?

The matcher code is generic and used by all importers. So the matcher page will always be shown even if all data is there. Usually in that case there's nothing to do on that page and you can just continue. However you may want to change the reconcile flag or do a final double-check you didn't make a mistake in previous steps of the import.

**Comment by DaveC49** [comment]
Import Accounts From CSV is not presented anywhere else

Then it should be before being used in an example--especially one titled "Pulling it all together".

John, Geert, Frank ,@flywire

I had noticed that sections covering CoA ( and other imports and exports) were needed in the help manual while updating the Importing transactions sections last year. The obvious place will be in the help manual section on account setup. Will try and add a section on that. 

We now have some duplication in the help manual and guide on importing transactions. My original intention was to remove the interface description from the guide to help and add some importing examples in Chapter 3 of the guide with cross referenceing back to the help manual.  I was a bit derailed in that exercise and have a branch in my repo with changes to Ch3 of the guide which deleted the duplication and added examples. I had intended to complete it then PR the lot, it but it may be better to do it in smaller sections. I had sections set up on a minimal info csv import and csv single line imports starting from had just started doing something on the multiline multisplit. In each case I had a short CSV file and followed it through the process. @Geert With the changes in 3.10 to the multiline imports I will revisit it again and try to PR it in sections.

**Comment by jralls** [comment]
@DaveC49 It's easier on everyone to do a bunch of small changes instead of a monster change, so +1 to that part.

Duplication is bad--the Help version has gotten some updates that the T&CG didn't get, illustrating the obvious problem that duplication quickly gets out of sync, so let's clean that out too. 

I'm ambivalent, though, about having the guide chapter on importing be only examples. I think there should be some introduction to the idea and an explanation of the different file types and tradeoffs for using one over another. The guide CSV import section could (should?) also explain the minimum required fields for the price and transaction importers and perhaps some of the finer points of presenting numbers (decimals vs. fractions), selecting columns (better to supply amount and value rather than amount and price for multi-currency), and perhaps other conceptual topics. 

I'll point out here that this PR is for `maint` and the time for significant changes to that branch is over: I've already started on the release notes for the first unstable release from `master` this weekend. That would apply to your pending PR(s) as well.

**Comment by fellen** [comment]
> I had noticed that sections covering CoA ( and other imports and exports) were needed in the help manual while updating the Importing transactions sections last year. The obvious place will be in the help manual section on account setup. Will try and add a section on that.

The description of the CoA is in https://code.gnucash.org/docs/C/gnucash-help/ch04s02.html. But I believe, you are talking about "Import Accounts from a CSV file" using the "CSV Import Assistant". ISTR that section was lost between Gnucash 1 and 2[?]. OTOH I have recently started to fill some gaps in gnucash-guide/appendixa_import.html [commit 9edbf25]. Perhaps we should merge that appendix with parts from chapter basics into an chapter "Starting with Gnucash": You can either start from scratch using the New_File assistant or by migrating your old data ...

**Comment by DaveC49** [comment]
Frank,
I was specifically thinking of the Import Accounts from a CSV File but as there is also the XML File-> Export Accounts which is then opened with File ->Open. It may pay to put these together and contrast the relative advantages of each approach in terms of which parts of the book setup are retained in the second case. At the end of Chapter 5 in the help manual which covers Setting Up, Editing & Working with Accounts would seem to be one possible place to perhaps cover the interfaces for these. I would see the main application/use case being when a user wants to open a new book with the same structure e.g. for those who create a new file periodically.
A Starting with GnuCash section in the guide sounds good with the two sections. You have to start with the NewFile Assistant in either case. A new user with little or no accounting experience is one possible target  audience and the second would be someone who is experienced in accounting practice generally but needs to setup and import data from another program and get working fairly quickly - e.g. more likely a business user.  It has been so long since I made the transition from MYOB to GnuCash that I remember very little of it. Are there other potential classes of new user we might need to target?
 I remember very little of my transition from MYOB to GnuCash now. I needed an accounting program to do tutorial exercises  and the minor thesis exercises in while I was doing a  masters in accounting 13 years ago. I was preparing accounts for a dummy business in a week or two without much problem.  GnuCash was ideal for that as there was very little detail hidden from the user. I had used MYOB in a business for several years which I had closed down by then and I was transitioning to just personal accounts and a few minor business activies just befor retiring so my needs are/were not on the onerous side.

**Comment by fellen** [comment]
> I was specifically thinking of the Import Accounts from a CSV File but as there is also the XML File-> Export Accounts which is then opened with File ->Open. It may pay to put these together and contrast the relative advantages of each approach in terms of which parts of the book setup are retained in the second case. At the end of Chapter 5 in the help manual which covers Setting Up, Editing & Working with Accounts would seem to be one possible place to perhaps cover the interfaces for these. I would see the main application/use case being when a user wants to open a new book with the same structure e.g. for those who create a new file periodically.

I think as rule of thumb we should follow the menu structure of the program. But as the corresponding elements of File->{Import|Export} have much in common, it might be better to join them. Also the current "5.2. Creating a Chart of Accounts" is close and should be joined or linked.

But the tutorial part should end close to gnucash-guide/basics-running-gnucash.html#basics-acct-hierarchy.

> A Starting with GnuCash section in the guide sounds good with the two sections. You have to start with the NewFile Assistant in either case. A new user with little or no accounting experience is one possible target audience and the second would be someone who is experienced in accounting practice generally but needs to setup and import data from another program and get working fairly quickly - e.g. more likely a business user. It has been so long since I made the transition from MYOB to GnuCash that I remember very little of it. Are there other potential classes of new user we might need to target?

Potential Scenarios:
- From Scratch: New Account Hierachy Assistant
--Private: Common + optional modules
--Business: e.g. en_IN:GSTIndia, but no other modules
  other examples de_DE:SKR*; _AT:EKR; _CH:KMU 
- Import existing data
-- QIF financial data from other financial app
--CSV: from spreadsheet, but also additional data like supplier, client, ...

> I remember very little of my transition from MYOB to GnuCash now. I needed an accounting program to do tutorial exercises and the minor thesis exercises in while I was doing a masters in accounting 13 years ago. I was preparing accounts for a dummy business in a week or two without much problem. GnuCash was ideal for that as there was very little detail hidden from the user. I had used MYOB in a business for several years which I had closed down by then and I was transitioning to just personal accounts and a few minor business activies just befor retiring so my needs are/were not on the onerous side.

**Comment by flywire** [comment]
The comments seem reasonable about csv being part of a broader process, and certainly a last option. The current location at the end of the _Getting Started_ Section before the _Managing Personal Finances_ is the right location, before gcashdata_4 is created and people do the setup.

The Bank Statement needs to transition to the one in [5.5.3. Opening Balances](https://www.gnucash.org/docs/v3/C/gnucash-guide/cbook-together1.html#cbook-puttoget-reconcile) with a description coded more like a bank statement than a CoA. People don't always have the full period of data when they download it and it really depends on how much transaction data is exposed by the end of the transaction section.

**Comment by flywire** [comment]
> Your assumption of some sort of unspecified preprocessor for CSV files

eg [BankCategories.xltx](https://drive.google.com/file/d/1FXN0mw_GaOzA3pGXSFAXK3R_Jk8mjpaZ/view?usp=sharing) (Click the Down-Arrow don't save from Google Docs) or for non-windows - [qifqif](https://github.com/Kraymer/qifqif)

I'd appreciate involvement in developing import data docs.

**Comment by DaveC49** [comment]
Please feel free to contribute to the importing section. I made a first pass attempt after Geert's rewrite of the code for the CSV so there are likely many deficiencies. The wiki has instructions on the process here https://wiki.gnucash.org/wiki/Documentation_Update_Instructions.

**Comment by flywire** [comment]
Just to be clear, you're referring to https://github.com/Gnucash/gnucash-docs/blob/maint/guide/C/ch_importing.xml (Master branch) which is the same as https://gnucash.org/viewdoc.phtml?rev=3&lang=C&doc=guide?

This PR was for a specific example and a lot of changes have been discussed. I'm not in a position within the community to lead these changes but I could make significant contributions once the document structure was agreed.

-----

Hmm ... those instructions are very detailed and there is no quick summary but it looks like quite a process.

Here's how [Setting Up Your System](https://wiki.gnucash.org/wiki/Documentation_Update_Instructions#The_Documentation_Change_Process) and [The Documentation Change Process](https://wiki.gnucash.org/wiki/Documentation_Update_Instructions#The_Documentation_Change_Process) could work:
- Assume document is a text-based markup language like [GnuCash Tutorial and Concepts Guide - Basics](https://gnucash-docs-rst.readthedocs.io/en/latest/guide/C/ch_basics.html)
- Click _'Edit on GitHub'_ at top of page
- Click the pencil icon
- _"You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork flywire/gnucash-docs-rst, so you can send a pull request."_

Certainly, a lot of the detail would still apply but it seems simpler, and no direct `git`.

**Comment by DaveC49** [comment]
The process is historical (possibly hysterical) and may possibly serves to insulate the main developers a bit from those of us with lesser skills in git and github. It also accommodates the reality that most of us have our own development setups and use our own favourite tools for editing, managing git/github etc. John, Frank, Derek and Geert can likely comment further on why we have the current process.

**Comment by gjanssens** [comment]
> Just to be clear, you're referring to https://github.com/Gnucash/gnucash-docs/blob/maint/guide/C/ch_importing.xml (Master branch) which is the same as https://gnucash.org/viewdoc.phtml?rev=3&lang=C&doc=guide?
> 
> This PR was for a specific example and a lot of changes have been discussed. I'm not in a position within the community to lead these changes but I could make significant contributions once the document structure was agreed.
> 
> Hmm ... those instructions are very detailed and there is no quick summary but it looks like quite a process.
> 
> Here's how [Setting Up Your System](https://wiki.gnucash.org/wiki/Documentation_Update_Instructions#The_Documentation_Change_Process) and [The Documentation Change Process](https://wiki.gnucash.org/wiki/Documentation_Update_Instructions#The_Documentation_Change_Process) could work:
> 
>     * Assume document is a text-based markup language like [GnuCash Tutorial and Concepts Guide - Basics](https://gnucash-docs-rst.readthedocs.io/en/latest/guide/C/ch_basics.html)
> 
>     * Click _'Edit on GitHub'_ at top of page
> 
>     * Click the pencil icon
> 
>     * _"You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork flywire/gnucash-docs-rst, so you can send a pull request."_
> 
> 
> Certainly, a lot of the detail would still apply but it seems simpler, and no direct `git`.

Sure, if you can write perfect docbook xml, feel free to do it like that now already :)

The build tools are there to offer validation techniques to documentation writers. The documentation is not just something that's available online. It also gets integrated in the gnucash application. The format required for that is different on each supported platform. The build tools help you generate and install the documentation in those various formats on your PC.

Github doesn't help with any of that. So if we tell contributors to just do submit pull requests based on the in place editor of github, all the extra validation burden falls on the shoulders of the few documentation committers. Currently those happen to be the same people that also want to find time to write the actual gnucash code. So the more they can offload to others the more time they get to effectively do that.

**Comment by gjanssens** [comment]
> Certainly, a lot of the detail would still apply but it seems simpler, and no direct `git`.

Oh, I should have mentioned we have done this experiment in the past even. One of the contributors then tried the "fork" method to create a simple PR. Exactly with the idea of hiding the git aspect of it. It turned out this didn't work at all but for the most trivial contributions: small one-off fly-by type contributions. Many of the git hurdles remained anyway:
- user selects the wrong base branch to make the change on
- user is asked to make amendments and gets lost in the concept of multiple commits
- after the merge user has to get his fork up to date with the main repository. This is not possible via the github interface without adding unwanted merge commits in the forked repo.
- if the user wants to contribute more than just a one-off, this gets all aggravated by the need to make multiple branches, the impossibility to pull without merge commits.
Really it went downhill quickly.

Based on that experience I much rather attract users that are comfortable with git or are capable of learning it. It tends to improve the quality of the contributions and lowers the maintenance burden.

**Comment by flywire** [comment]
> The documentation... gets integrated in the gnucash application.

I didn't appreciate that, it explains why it's done in a coding environment. I've used git for code, just normally way over the top for a dozen doc files.

**Pull request closed without merging**
